// chosenCityReducer
export const FETCH_AVAILBE_COUNTRES = 'FETCH_AVAILBE_COUNTRES';
export const FETCH_NEAREST_CITY = 'FETCH_NEAREST_CITY';
export const FETCH_STATE_IN_COUNTRY = 'FETCH_STATE_IN_COUNTRY';
export const FETCH_CITIES_IN_STATE = 'FETCH_CITIES_IN_STATE';
export const FETCH_SPECIFIED_DATA_FROM_CITY = 'FETCH_SPECIFIED_DATA_FROM_CITY';

// choiceReducer
export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const FETCH_STATE = 'FETCH_STATE';
export const FETCH_CITY = 'FETCH_CITY';
