// chosenCityReducer
export const FETCH_AVAILBE_COUNTRES = 'FETCH_AVAILBE_COUNTRES';
export const FETCH_NEAREST_CITY = 'FETCH_NEAREST_CITY';
export const FETCH_STATE_IN_COUNTRY = 'FETCH_STATE_IN_COUNTRY';

